"""replace badge with status in properties

Revision ID: 613457953274
Revises: 
Create Date: 2025-06-23 13:54:59.086108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '613457953274'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.drop_column('badge')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('badge', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
